export default {
    baldur_card_name: "Baldur",
    baldur_card_description: "Baldur jest znany z dobrej walki ciężkim mieczem.",
    snake_storm_card_name: "Deszcz Węży",
    snake_storm_card_description: "Taki wąż potrafi zabić jednym ukąszeniem.",
    loki_card_name: "Loki",
    loki_card_description: "Loki zjednoczył wiele plemion w jeden kraj.",
    hajmdal_card_name: "Hajmdal",
    hajmdal_card_description: "Hajmdal strzela z łuku zrobionego z wierzby.",
    magni_card_name: "Magni",
    magni_card_description: "Magni podczas bitwy pomaga z dystansu.",
    archers_thrudheim_card_name: "Łucznicy z Thrudheim",
    archers_thrudheim_card_description: "Z Thrudheim pochodzą najlepsi łucznicy.",
    aegir_card_name: "Aegir",
    aegir_card_description: "Aegir potrafi bezszelestnie chodzić.",
    hodur_card_name: "Hodur",
    hodur_card_description: "Hodur nie przegrał nigdy żadnego pojedynku.",
    frigg_card_name: "Frigg",
    frigg_card_description: "Frigg podobno potrafi latać na miotle.",
    fulla_card_name: "Fulla",
    fulla_card_description: "Fulla jest bardzo znaną czarodziejką.",
    widar_card_name: "Widar",
    widar_card_description: "Widar w starym języku oznacza “milczący”.",
    forseti_card_name: "Forseti",
    forseti_card_description: "Forseti mieszka w pałacu ze złotymi kolumnami.",
    arrow_storm_card_name: "Deszcz strzał",
    arrow_storm_card_description: "Strzały spadające z nieba mogą roztrzygnąć wynik potyczki.",
    young_giant_card_name: "Młody Olbrzym",
    young_giant_card_description: "Nawet młody olbrzym jest większy od dorosłego człowieka.",
    rock_storm_card_name: "Deszcz kamieni",
    rock_storm_card_description: "Kamienie mogą rozwalić czyjąś czaszkę.",
    hermod_card_name: "Hermod",
    hermod_card_description: "Powiadają, że Hermod został posłany na świat przez Bogów.",
    kvaser_card_name: "Kvaser",
    kvaser_card_description: "Kvaser zna odpowiedź na każde pytanie.",
    sigyn_card_name: "Sigyn",
    sigyn_card_description: "Sigyn jest synem olbrzyma i kobiety.",
    freja_card_name: "Freja",
    freja_card_description: "Freja w czasie bitwy jeździ na swoim dziku.",
    boar_horde_card_name: "Horda dzików",
    boar_horde_card_description: "Przed głodnymi dzikami za daleko nie uciekniesz.",
    battered_carapulte_card_name: "Podniszczona katapulta",
    battered_catapulte_card_description: "Katapulta w nienajlepszym stanie nadal spełnia swoje zadanie.",
    hel_card_name: "Hel",
    hel_card_description: "Hel jest jednym z największych wojowników.",
    mimir_card_name: "Mimir",
    mimir_card_description: "Mimir pomimo swojego wieku bardzo dobrze walczy.",
    ax_launcher_card_name: "Wyrzutnia toporów",
    ax_launcher_card_description: "Nikt nie chciałby dostać takim toporem w głowę.",
    sol_card_name: "Sol",
    sol_card_description: "Legenda mówi, że Sol urodził się na słońcu.",
    mani_card_name: "Mani",
    mani_card_description: "Mani bardzo szybko biega.",
    gullweig_card_name: "Gullweig",
    gullweig_card_description: "Gullweig podobno potrafi używać magii.",
    wolf_horde_card_name: "Horda wilków",
    wolf_horde_card_description: "Wilki przestraszą nawet najbardziej odważnych wojowników.",
    support_from_gods_card_name: "Wsparcie od Bogów",
    support_from_gods_card_description: "Modlitwa do Bogów czyni cuda.",
    morrigan_card_name: "Morrigan",
    morrigan_card_description: "Mędrzec, który podobno potrafi rozmawiać z Bogiem.",
    dagda_card_name: "Dagda",
    dagda_card_description: "Najdzielniejszy rycerz w kraju.",
    belenus_card_name: "Belenus",
    belenus_card_description: "Belenus walczy zakrzywionym mieczem.",
    lug_card_name: "Lug",
    lug_card_description: "Lug walczy ramię w ramię ze swoim wilkiem.",
    catapult_card_name: "Katapulta",
    catapult_card_description: "Katapulta pozwala atakować z daleka.",
    lukan_card_name: "Lukan",
    lukan_card_description: "Lukan strzela z długiego łuku.",
    ballista_card_name: "Balista",
    ballista_card_description: "Balista trafia do celu nawet z 800 metrów.",
    icestorm_card_name: "Gradobicie",
    icestorm_description: "Kule gradu mogą zabić wrogą armię.",
    carousel_card_name: "Hulajgród",
    carousel_description: "Hulajgród jest nowoczesną machiną oblężniczą.",
    jonsi_card_name: "Jonsi",
    jonsi_card_description: "Jonsi to druid, który potrafi wyleczyć każdą chorobę.",
    ibar_druids_card_name: "Druidzi z Ibar",
    ibar_druids_card_description: "Druidzi nie rozstają się ze swoimi cisowymi laskami.",
    brigit_card_name: "Brigit",
    brigit_card_description: "Brigit jest największym wojownikiem-kobietą.",
    taranis_card_name: "Taranis",
    taranis_card_description: "Taranis pije tylko wino.",
    esus_card_name: "Esus",
    esus_card_description: "Esus przed walką odprawia nabożeństwo dla całej armii.",
    galahad_card_name: "Galahad",
    galahad_card_description: "Galahad już od małego chciał zostać wielkim rycerzem.",
    aibell_card_name: "Aibell",
    aibell_card_description: "Aibell została wychowana przez druidów.",
    uther_card_name: "Uther",
    uther_card_description: "Uther jest znanym w kraju wynalazcą.",
    talitia_card_name: "Talitia",
    talitia_card_description: "Talitia bardzo dobrze strzela z sosnowego łuku.",
    arthwys_card_name: "Arthwys",
    arthwys_card_description: "Arthwys napisał już wiele książek na temat sztuki wojennej.",
    gray_lines_card_name: "Szare szeregi",
    gray_lines_card_description: "Szare Szeregi to kilkuosobowe grupy skrytobójców.",
    gwynedd_card_name: "Gwynedd",
    gwynedd_card_description: "Gwynedd jest przywódcą krasnolódów z pobliskiej wsi.",
    ostenda_infantry_card_name: "Piechurzy z Ostendy",
    ostenda_infantry_description: "Akademia Wojskowa w Ostendzie kształci najlepszych żołnierzy.",
    armed_peasants_card_name: "Uzbrojeni wieśniacy",
    armed_peasants_card_description: "Zostali zwerbowani prosto z pola. Walczą przyrządami rolniczymi.",
    powys_launcher_card_name: "Powys",
    powys_card_description: "Powys jest w armii mistrzem oblężeń.",
    owain_card_name: "Owain",
    owain_card_description: "Owain potrafi się bezgłośnie przedostać na tyły wroga.",
    hero_attribute_name: "Bohater",
    hero_attribute_description: "Odporność na działanie kart specjalnych i efektów pogodowych.",
    medic_attribute_name: "Medyk",
    medic_attribute_description: "Wybierz jedną kartę ze stosu swoich kart odrzuconych.",
    spy_attribute_name: "Szpieg",
    spy_attribute_description: "Umieść kartę na polu wroga (dodaje sił do szeregu) i weź dwie losowe karty ze swojej talii.",
    bond_attribute_name: "Więź",
    bond_attribute_description: "Umieść kartę obok podobnie nazwanej karty, żeby podwoić ich siły.",
    supply_attribute_name: "Wsparcie",
    supply_attribute_description: "Dodaje+1 do wszystkich jednostek poza sobą.",
    cold_attribute_name: "Trzaskający mróz",
    cold_attribute_description: "Efekt pogodowy. Wszystkie jednostki walczące w zwarciu, otrzymują wartość 1, dla obu graczy.",
    rain_attribute_name: "Deszcz",
    rain_attribute_description: "Efekt pogodowy. Wszystkie jednostki oblężnicze otrzymują wartość 1 dla obu graczy.",
    fog_attribute_name: "Mgła",
    fog_attribute_description: "Efekt pogodowy. Wszystkie jednostki walczące na dystans otrzymują wartość 1 dla obu graczy.",
    good_weather_attribute_name: "Czyste niebo",
    good_weather_attribute_description: "Usuwa wszystkie efekty pogodowe.",
    commanders_horn_attribute_name: "Róg dowódcy",
    commanders_horn_attribute_description: "Wysokie morale. Podwaja siłę jednostek w danym rzędzie.",
    scourge_attribute_name: "Plaga",
    scourge_attribute_description: "Niszczy najsilniejsze jednostki na planszy",
};
